### ISSUE TITLE
edm中的变化

### ISSUE THREAD

**Issue by CBQ-1223** [woodfrog/poly-diffuse#10]
请教个问题大佬,代码这里:
model_in = (c_in * x).to(dtype) + (1 - c_in) * mu_guide.to(dtype)
ed中加入(c_in * x)是为了将输入方差变为1,您后面加的这项1 - c_in) * mu_guide.to(dtype)的目地是什么呢,是为了把引导网络的均值给引入进去吗

**Comment by CBQ-1223** [comment]
还有就是在训练denoise网络的时候,
        mu_guide, sigma_guide = net_guide(images, attn_mask, poly_class)
        mu_guide = mu_guide[:, :, None, :]
        n = torch.randn_like(y) * sigma[..., None] * sigma_guide[:, :, None, :]
        noised_y = y + n
您给添加的噪声乘以了sigma_guide,但是在denoise的时候,没有添加这一项,是默认初始化的噪声分布服从根据元素而乘以sigma_guide这样的分布吗

**Comment by CBQ-1223** [comment]
大佬您要是不太看信息可以加个wechat吗，后续会基于您的这篇工作做更端到端的矢量化生成任务，有一些您代码中不理解的想请教您一下，我加您也行，我的wechat：19818987510

**Comment by woodfrog** [comment]
这些你把代码对应的公式写一遍就都清楚了。代码里的[``model_in``](https://github.com/woodfrog/poly-diffuse/blob/7b48bec1917a4eac738715bb8921b2b50b94e533/src/models/networks.py#L50)和DDPM的x_t是一个东西。要是写出来以后还不清楚的话就把EDM和DDPM再读一下。
