### ISSUE TITLE
conda error

### ISSUE THREAD

**Issue by liangxuejingjing** [woodfrog/poly-diffuse#2]
Hi, thanks a lot for releasing this code. But when I installed this environment, I met some errors.

1.  directly `sudo sh make.sh`-> `ModuleNotFoundError: No module named 'torch'`, I don't know why.
2. If I use a docker to install, I met [https://discuss.pytorch.org/t/not-able-to-include-cusolverdn-h/169122/3] and `export PATH=/usr/local/cuda/bin:$PATH ` can't deal with it.

So, what can I do?

**Comment by woodfrog** [comment]
Did you install the conda environment first? The ``make.sh`` for the deformable attention module should be complied after installing and activating the conda environment.

**Comment by liangxuejingjing** [comment]
> Did you install the conda environment first? The `make.sh` for the deformable attention module should be complied after installing and activating the conda environment.
![b212ec02089f51936292b06d8c985cd](https://github.com/woodfrog/poly-diffuse/assets/34302426/df4948cf-bab1-4833-88f7-914e077843d6)
yes, I install the conda environment.

**Comment by woodfrog** [comment]
> > Did you install the conda environment first? The `make.sh` for the deformable attention module should be complied after installing and activating the conda environment.
> > ![b212ec02089f51936292b06d8c985cd](https://user-images.githubusercontent.com/34302426/252847079-df4948cf-bab1-4833-88f7-914e077843d6.png)
> > yes, I install the conda environment.

Then the installation must fail at some point. Maybe first check if all the necessary libraries are installed.
