### ISSUE TITLE
normal map in dataloader

### ISSUE THREAD

**Issue by jdk9405** [woodfrog/poly-diffuse#4]
Hello, Thank you for sharing the amazing work!

I have a question about the "normal" parameter in the dataloader: 
https://github.com/woodfrog/poly-diffuse/blob/main/src/datasets/polygon_datasets.py#L50
I noticed that normal maps consist of values of either 0 or 255.
How can I preprocess my custom dataset to get the normal map before testing your code?

**Comment by woodfrog** [comment]
Hi, thanks for your interest. This normal issue seems to be inherited from an early work, MonteFloor, which provides the data pre-processing scripts for the Structured3D dataset. You can refer to [this issue](https://github.com/woodfrog/heat/issues/10) in my other repo for reference.

**Comment by jdk9405** [comment]
Thank you for the quick response. I'll refer to the link.
