### ISSUE TITLE
Generate density images from point cloud top view

### ISSUE THREAD

**Issue by aditdoshi333** [woodfrog/poly-diffuse#5]
Hello,

Thanks for sharing the work. I want to run the inference pipeline and have images of the point cloud from the top view. How to create a density map from the same?

Please share!

**Comment by woodfrog** [comment]
Hi,

Thanks for your interest. You can refer to the preprocessing part in my other repo [here](https://github.com/woodfrog/heat/blob/master/s3d_preprocess/DataProcessing/FloorRW.py#L62C67-L62C83). These preprocessing utils for Structured3D data were inherited from a previous paper, MonteFloor, and you can check my [README](https://github.com/woodfrog/heat/tree/master/s3d_preprocess) in that repo for more details.
