### ISSUE TITLE
change supported image size in floorplan reconstruction task 

### ISSUE THREAD

**Issue by 920902021** [woodfrog/poly-diffuse#6]
Hello, 

I wan't to train the poly-diffuse with my own dataset, but my dataset is not suitable for scaling to 256*256, how can I change the poly-diffuse's code to support other image size?

Please share! Thanks.

**Comment by woodfrog** [comment]
Hi, I believe you only need to change the data loading part of the code and train the models using your data. Concretely,  1) set the input image size to your custom size; 2) make sure the vector annotations align with your custom size; 3) train the models with your custom data. BTW, I guess you are referring to the floorplan data. In this case, you might also need to re-train the Roomformer on your custom data to produce the initial solution.
