### ISSUE TITLE
【HD MAPPING】GT and input from init maptr seems not a same time

### ISSUE THREAD

**Issue by yHsi** [woodfrog/poly-diffuse#7]
I have get the test result based on hd mapping branch with nuscenes mini dataset.  But I found GT and input from init maptr seems not a same time reviewing the output. 
Output as following:
 1_GT_fixednum_pts_MAP:
![1_GT_fixednum_pts_MAP](https://github.com/woodfrog/poly-diffuse/assets/32357130/42ab206b-2618-4cd6-9963-8e4848a712e7)
1_maptr_pred:

**Comment by yHsi** [comment]
1_maptr_pred:
![1_maptr_pred](https://github.com/woodfrog/poly-diffuse/assets/32357130/1abdb694-9834-42dd-b753-d828d29b1382)

**Comment by woodfrog** [comment]
The problem might come from your use of nuScenes-mini dataset -- I used the full nuScenes dataset and exported MapTR's outputs as the initial proposals. If you run with nuScenes-mini, you will need to run MapTR on the mini dataset and use the saved JSON file as the initial proposals.
