### ISSUE TITLE
一些疑惑和请教

### ISSUE THREAD

**Issue by CBQ-1223** [woodfrog/poly-diffuse#8]
大佬好，有两个地方想和您请教一下，1.您说的这种加噪避免歧义性，我这样理解对吗：
比如有4个polygon abcd，加噪之后去噪，diffusion其实想做的是让加噪的abcd，分别按照原本的abcd的还原方向去噪，而不是会出现比如把加噪的abcd按照分别是按dcba的方向去噪，使得加噪的a去噪也就是朝着原本的a方向去噪
2.按照您论文中说的，这种方式·很依赖propose generator，比如maptr，这种方式不会产生新实例只能微调，大佬有啥好的思路嘛，还是说如果没有这个propose generator做过一些尝试效果不好呢？大佬有什么想法或者别的领域参考论文可以交流嘛，或者加个wx？

**Comment by woodfrog** [comment]
不好意思之前没看到。

1. 大致是这个意思。按论文里Fig.2的例子，你说的a、b、c、d是一个polygon的permutation equivalent representation。

2. 目前这个方法的formulation没有包含对 i) polygon数量 和 ii)每个polygon的vertex数量 的估计，所以需要从proposal generator来得到这两个信息。polygon/vertex数量是离散的，坐标是连续的，这个方法主要目的还是想用diffusion model去更精确地估计vertex坐标（连续变量），从而更准确地重建polygon的shape，没尝试过没有proposal直接denoise所有变量的情况。这边如果要同时denoise离散和连续变量的话肯定需要一个更好的设计，特别是polygon/vertex数量的变化会改变拓扑。

**Comment by CBQ-1223** [comment]
> 不好意思之前没看到。
> 
> 1. 大致是这个意思。按论文里Fig.2的例子，你说的a、b、c、d是一个polygon的permutation equivalent representation。
> 2. 目前这个方法的formulation没有包含对 i) polygon数量 和 ii)每个polygon的vertex数量 的估计，所以需要从proposal generator来得到这两个信息。polygon/vertex数量是离散的，坐标是连续的，这个方法主要目的还是想用diffusion model去更精确地估计vertex坐标（连续变量），从而更准确地重建polygon的shape，没尝试过没有proposal直接denoise所有变量的情况。这边如果要同时denoise离散和连续变量的话肯定需要一个更好的设计，特别是polygon/vertex数量的变化会改变拓扑。

> 不好意思之前没看到。
> 
> 1. 大致是这个意思。按论文里Fig.2的例子，你说的a、b、c、d是一个polygon的permutation equivalent representation。
> 2. 目前这个方法的formulation没有包含对 i) polygon数量 和 ii)每个polygon的vertex数量 的估计，所以需要从proposal generator来得到这两个信息。polygon/vertex数量是离散的，坐标是连续的，这个方法主要目的还是想用diffusion model去更精确地估计vertex坐标（连续变量），从而更准确地重建polygon的shape，没尝试过没有proposal直接denoise所有变量的情况。这边如果要同时denoise离散和连续变量的话肯定需要一个更好的设计，特别是polygon/vertex数量的变化会改变拓扑。

好嘞好嘞，谢谢大佬，明白啦～
