### ISSUE TITLE
formula of code  paper has gap

### ISSUE THREAD

**Issue by CBQ-1223** [woodfrog/poly-diffuse#9]
<img width="889" alt="948fc0ec39932288743dafd38" src="https://github.com/woodfrog/poly-diffuse/assets/77671882/efdf198c-e730-47b8-8c2d-2f4f4ddd62c8">

The formula (7) you provided in the paper is shown in the figure, but the noise addition formula I see in the code is:

```python
n = torch.randn_like(y) * sigma[..., None] * sigma_guide[:, :, None, :]
noised_y = y + n
```

Is there a gap between the formula and the code?

**Comment by woodfrog** [comment]
Our code is adapted from [EDM](https://github.com/NVlabs/edm), while the derivations in the paper are based on DDPM. Following Sec.5 of the EDM paper, the code you referred to can be converted to our equations in the paper.
